// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epnfdzktvxieczmlrawg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwbmZkemt0dnhpZWN6bWxyYXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDkzMDYsImV4cCI6MjA2OTgyNTMwNn0.NmXciPU4d-lgOILhEx77LisdQLZdfsZSAB1LCnqN6Uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});