// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bebbodrjkjcigfjjvhnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlYmJvZHJqa2pjaWdmamp2aG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxODY5MjQsImV4cCI6MjA2Nzc2MjkyNH0.PDJ-ZrPO5sJ7t8RyocGDDdkt1WqeTh5s9m4rvzzB6CA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});